set nobackup  "不备份
"set cursorline "当前行高亮
set nu
nnoremap <leader>N :setlocal number!<cr>
let mapleader = '\' 
let g:mapleader = '\'

"替换快捷
noremap // :%s/\v

"排序快捷
noremap <leader>s :sort r /

noremap <F10> :w !sudo tee %<cr>
noremap ;; :%s:::g<Left><Left><Left>
noremap ;' :%s:::cg<Left><Left><Left><Left>

"ip-->cisco ip-->junper
noremap <F6> :%s:\v(((\d){1,3}\.){3}(\d){1,3}):ip route \1 255.255.255.255 10.15.245.45:g<left><left>
noremap <F7> :%s:\v(((\d){1,3}\.){3}(\d){1,3}):set routing-options static route \1/32 next-hop 10.40.0.206:g<Left><Left>

"打开vimrc                          
nnoremap <leader>ev :vsplit $MYVIMRC<cr>                           
                          
"重读vimrc                                   
nnoremap <leader>sv :source $MYVIMRC<cr>

"colorscheme desert "配色方案

"split navigations
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>
" :sv 纵向打开一个文件
" :vs 横向打开一个文件

"当前单词增加""
nnoremap <leader>" viw<esc>a"<esc>hbi"<esc>lel
"引号将你 高亮选中 的文本包裹
vnoremap <leader>" <esc><esc>`<i"<esc>`>a"

"jk代替<esc>
inoremap jk <esc>

"缩写
iabbrev @@ apache3@foxmail.com

set fileencodings=utf-8,gbk,cp936,gb18030,big5,euc-jp,euc-kr,latin1,ucs-bom,ucs
set fencs=utf-8,gbk,cp936,gb18030,gb2312,ucs-bom
"set enc=utf-8
set fenc=utf-8 "无论所打开文件是否为utf-8编码，保存时都会强制保存为utf-8格式
"set cindent  "自动对齐

set shiftwidth=4 
set tabstop=4 "让一个tab等于4个空格
set expandtab
set hlsearch "高亮显示结果
set incsearch "在输入要搜索的文字时，vim会实时匹配

set foldmethod=indent
set foldlevel=99
 
" press space to fold/unfold code
nnoremap <space> za
vnoremap <space> zf
                                
set laststatus=2 " Always display the statusline in all windows
set noshowmode " Hide the default mode text (e.g. -- INSERT -- below the statusline)

hi CursorLine   cterm=NONE ctermbg=darkred ctermfg=white guibg=darkred guifg=white 

"词典
function! Mydict()
    let expl=system('sdcv -n ' . 
                \ expand("<cword>"))
    windo if
                \ expand("%") == "diCt-tmp"|
                \ q!|endif
    25vsp diCt-tmp
    setlocal buftype=nofile bufhidden=hide noswapfile
    1s/^/\=expl/
    1
endfunction
nnoremap F :call Mydict()<cr>

" vundle
set nocompatible              " be iMproved, required
"filetype off                  " required
set rtp+=~/.vim/bundle/Vundle.vim
set rtp+=~/.vim/bundle/*
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
"Plugin 'kevinw/pyflakes-vim'
    filetype plugin indent on
Plugin 'scrooloose/nerdtree'
Plugin 'Xuyuanp/nerdtree-git-plugin'
    " nerdtree
    let g:NERDTreeIndicatorMapCustom = {
        \ "Modified"  : "✹",
        \ "Staged"    : "✚",
        \ "Untracked" : "✭",
        \ "Renamed"   : "➜",
        \ "Unmerged"  : "═",
        \ "Deleted"   : "✖",
        \ "Dirty"     : "✗",
        \ "Clean"     : "✔︎",
        \ "Unknown"   : "?"
        \ }
    "let NERDTreeWinPos='right'
    let NERDTreeWinSize=30
    map <F2> :NERDTreeToggle<CR>
Bundle 'bling/vim-airline'
    set laststatus=2
Plugin 'kien/ctrlp.vim'
    "超级搜索 ctrl + p
Plugin 'jnurmine/Zenburn' "配色
Plugin 'altercation/vim-colors-solarized' "配色
    if has('gui_running')
        set background=dark
        colorscheme solarized
        set guifont=DejaVu\ Sans\ mono\ 12 
    else
        colorscheme zenburn
    endif
"Bundle 'Valloric/YouCompleteMe' 
Bundle 'scrooloose/nerdcommenter'
    "快捷键 \cc 注释
    "       \cu 取消注释
Plugin 'othree/xml.vim' "xml/html标签自动闭合
Plugin 'Shougo/neocomplcache.vim' "自动补全
    "Note: This option must set it in .vimrc(_vimrc).  NOT IN .gvimrc(_gvimrc)!
    " Disable AutoComplPop.
    let g:acp_enableAtStartup = 0
    " Use neocomplcache.
    let g:neocomplcache_enable_at_startup = 1
    " Use smartcase.
    let g:neocomplcache_enable_smart_case = 1
    " Set minimum syntax keyword length.
    let g:neocomplcache_min_syntax_length = 3
    let g:neocomplcache_lock_buffer_name_pattern = '\*ku\*'

    " Enable heavy features.
    " Use camel case completion.
    "let g:neocomplcache_enable_camel_case_completion = 1
    " Use underbar completion.
    "let g:neocomplcache_enable_underbar_completion = 1

    " Define dictionary.
    let g:neocomplcache_dictionary_filetype_lists = {
        \ 'default' : '',
        \ 'vimshell' : $HOME.'/.vimshell_hist',
        \ 'scheme' : $HOME.'/.gosh_completions'
            \ }

    " Define keyword.
    if !exists('g:neocomplcache_keyword_patterns')
        let g:neocomplcache_keyword_patterns = {}
    endif
    let g:neocomplcache_keyword_patterns['default'] = '\h\w*'

    " Plugin key-mappings.
    inoremap <expr><C-g>     neocomplcache#undo_completion()
    inoremap <expr><C-l>     neocomplcache#complete_common_string()

    " Recommended key-mappings.
    " <CR>: close popup and save indent.
    inoremap <silent> <CR> <C-r>=<SID>my_cr_function()<CR>
    function! s:my_cr_function()
      return neocomplcache#smart_close_popup() . "\<CR>"
      " For no inserting <CR> key.
      "return pumvisible() ? neocomplcache#close_popup() : "\<CR>"
    endfunction
    " <TAB>: completion.
    inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
    " <C-h>, <BS>: close popup and delete backword char.
    inoremap <expr><C-h> neocomplcache#smart_close_popup()."\<C-h>"
    inoremap <expr><BS> neocomplcache#smart_close_popup()."\<C-h>"
    inoremap <expr><C-y>  neocomplcache#close_popup()
    inoremap <expr><C-e>  neocomplcache#cancel_popup()
    " Close popup by <Space>.
    "inoremap <expr><Space> pumvisible() ? neocomplcache#close_popup() : "\<Space>"

    " For cursor moving in insert mode(Not recommended)
    "inoremap <expr><Left>  neocomplcache#close_popup() . "\<Left>"
    "inoremap <expr><Right> neocomplcache#close_popup() . "\<Right>"
    "inoremap <expr><Up>    neocomplcache#close_popup() . "\<Up>"
    "inoremap <expr><Down>  neocomplcache#close_popup() . "\<Down>"
    " Or set this.
    "let g:neocomplcache_enable_cursor_hold_i = 1
    " Or set this.
    "let g:neocomplcache_enable_insert_char_pre = 1

    " AutoComplPop like behavior.
    "let g:neocomplcache_enable_auto_select = 1

    " Shell like behavior(not recommended).
    "set completeopt+=longest
    "let g:neocomplcache_enable_auto_select = 1
    "let g:neocomplcache_disable_auto_complete = 1
    "inoremap <expr><TAB>  pumvisible() ? "\<Down>" : "\<C-x>\<C-u>"

    " Enable omni completion.
    autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
    autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
    autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
    autocmd FileType python setlocal omnifunc=pythoncomplete#Complete
    autocmd FileType xml setlocal omnifunc=xmlcomplete#CompleteTags

    " Enable heavy omni completion.
    if !exists('g:neocomplcache_force_omni_patterns')
      let g:neocomplcache_force_omni_patterns = {}
    endif
    let g:neocomplcache_force_omni_patterns.php = '[^. \t]->\h\w*\|\h\w*::'
    let g:neocomplcache_force_omni_patterns.c = '[^.[:digit:] *\t]\%(\.\|->\)'
    let g:neocomplcache_force_omni_patterns.cpp = '[^.[:digit:] *\t]\%(\.\|->\)\|\h\w*::'

    " For perlomni.vim setting.
    " https://github.com/c9s/perlomni.vim
    let g:neocomplcache_force_omni_patterns.perl = '\h\w*->\h\w*\|\h\w*::'
Plugin 'hotoo/pangu.vim' "盘古插件用于自动格式化、标准化中文排版
    autocmd BufWritePre *.markdown,*.md,*.text,*.txt,*.wiki,*.cnx call PanGuSpacing()
    "功能
    "
    "中英文字符间增加一个半角空白。
    "中文前后的半角标点转成全角标点。
    "全角英文、数字转成半角字符。
    "连续的句号自动转省略号。
    "感叹号、问号最多允许连续重复 3 次。
    "其他中文标点符号不允许重复出现。
